services:
  front:
    build: ./front
    ports:
      - '3000:80'
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - '8080:8080'
    environment:
      - DB_NAME=f1shop
      - POSTGRES_USER=f1shop
      - POSTGRES_PASSWORD=f1shop348233083
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "f1shop", "-d", "f1shop" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: f1shop
      POSTGRES_USER: f1shop
      POSTGRES_PASSWORD: f1shop348233083
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
