security:
  jwt:
    secret-sey: verysecretkeydonttellanybodyimserious

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:f1_shop}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: always