CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email    VARCHAR(320) NOT NULL,
    password VARCHAR(40)  NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(320)  NOT NULL,
    description VARCHAR(2000) NOT NULL,
    image_link  VARCHAR(1000) NOT NULL,
    price       REAL          NOT NULL,
    count       INTEGER       NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_products
(
    user_id    BIGINT REFERENCES users (id)    NOT NULL,
    product_id BIGINT REFERENCES products (id) NOT NULL,
    count      INTEGER                         NOT NULL
);

CREATE TABLE IF NOT EXISTS wishlist_products
(
    user_id    BIGINT REFERENCES users (id)    NOT NULL,
    product_id BIGINT REFERENCES products (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT REFERENCES users (id) NOT NULL,
    date    TIMESTAMP                    NOT NULL
);

CREATE TABLE IF NOT EXISTS order_products
(
    order_id   BIGINT REFERENCES orders (id)   NOT NULL,
    product_id BIGINT REFERENCES products (id) NOT NULL,
    count      INTEGER                         NOT NULL
);