export const dataBase = [
    {
        id: 1,
        category: "Кепки",
        price: 2499,
        image: "../images/кепка феррари вегас.webp",
        name: "Кепка Ferrari Vegas GP",
        description: "",
    },
    {
        id: 2,
        category: "Худи",
        price: 6999,
        image: "../images/худи мермедес.webp",
        name: "Худи Mercedes Stealth",
        description: "",
    },
    {
        id: 3,
        category: "Худи",
        price: 14990,
        image: "../images/худи ферари.webp",
        name: "Худи Ferrari Leclerc Vegas GP",
        description: "",
    },
    {
        id: 4,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка алонсо.webp",
        name: "Кепка Aston Martin Alonso 14",
        description: "",
    },
    {
        id: 5,
        category: "Модели",
        price: 3499,
        image: "../images/лего w12.webp",
        name: "Lego Speed Champions Mercedes W12 & Mercedes-AMG One",
        description: "",
    },
    {
        id: 6,
        category: "Модели",
        price: 19900,
        image: "../images/лего макларен.webp",
        name: "Lego McLaren Formula 1 car",
        description: "",
    },
    {
        id: 7,
        category: "Модели",
        price: 39990,
        image: "../images/модель w13.jpg",
        name: "Модель Mercedes W13 Russel 1:18",
        description: "1:18",
    },
    {
        id: 8,
        category: "Модели",
        price: 34990,
        image: "../images/модель ferrari sf23.jpg",
        name: "Модель Ferrari SF-23 Sainz 1:23",
        description: "",
    },
    {
        id: 9,
        category: "Футболки",
        price: 1499,
        image: "../images/футболка ferrari.jpg",
        name: "Футболка Ferrari 2023",
        description: "",
    },
    {
        id: 10,
        category: "Футболки",
        price: 1499,
        image: "../images/футболка red bull.jpg",
        name: "Футболка Red Bull 2023",
        description: "",
    },
    {
        id: 11,
        category: "Футболки",
        price: 1499,
        image: "../images/футболка mercedes.png",
        name: "Футболка Mercedes 2023",
        description: "",
    },
    {
        id: 12,
        category: "Футболки",
        price: 1999,
        image: "../images/футболка NOR_4.png",
        name: "Футболка Lando Norris",
        description: "",
    },
    {
        id: 13,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка ferrari.jpg",
        name: "Кепка Ferrari Leclerc 16",
        description: "",
    },
    {
        id: 14,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка red bull.jpg",
        name: "Кепка Red Bull Verstappen",
        description: "",
    },
    {
        id: 15,
        category: "Постеры",
        price: 899,
        image: "../images/постер ver.jpg",
        name: "Постер Max Verstappen Red Bull WC",
        description: "",
    },
    {
        id: 16,
        category: "Постеры",
        price: 899,
        image: "../images/постер lec.png",
        name: "Постер Ferrari Charles Leclerc",
        description: "",
    },
    {
        id: 17,
        category: "Худи",
        price: 3499,
        image: "../images/худи мерседес.png",
        name: "Худи Mercedes 2023",
        description: "",
    },
    {
        id: 18,
        category: "Худи",
        price: 3499,
        image: "../images/худи феррари.jpg",
        name: "Худи Ferrari 2023",
        description: "",
    },
    {
        id: 19,
        category: "Худи",
        price: 3499,
        image: "../images/худи red bull.jpg",
        name: "Худи Red Bull 2023",
        description: "",
    },
    {
        id: 20,
        category: "Календари",
        price: 899,
        image: "../images/календарь hamilton.png",
        name: "Календарь 2024 Mercedes Hamilton",
        description: "",
    },
    {
        id: 21,
        category: "Календари",
        price: 899,
        image: "../images/календарь red bull.png",
        name: "Календарь 2024 Red Bull Verstappen",
        description: "",
    },
    {
        id: 22,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка pirelli.jpg",
        name: "Кепка Pirelli 1st",
        description: "",
    },
    {
        id: 23,
        category: "Шлемы",
        price: 19990,
        image: "../images/шлем leclerc.webp",
        name: "Шлем Leclerc 16 Ferrari 2023 1:2",
        description: "",
    },
    {
        id: 24,
        category: "Шлемы",
        price: 23990,
        image: "../images/шлем Перс австрия.webp",
        name: "Шлем Perez 11 Red Bull 2022 Austria GP 1:2",
        description: "",
    },
    {
        id: 25,
        category: "Шлемы",
        price: 29990,
        image: "../images/Шлем шумахер 2000.webp",
        name: "Шлем Schumacher 2000 Ferrari WC 1:2",
        description: "",
    },
    {
        id: 26,
        category: "Шлемы",
        price: 26990,
        image: "../images/шлем Перес 2023.webp",
        name: "Шлем Perez 11 Red Bull 2023 1:2",
        description: "",
    },
    {
        id: 27,
        category: "Модели",
        price: 46990,
        image: "../images/модель феррари монца.webp",
        name: "Модель Ferrari F75 Monza Leclerc 1:18",
        description: "",
    },
    {
        id: 28,
        category: "Худи",
        price: 13490,
        image: "../images/худи Мерседес 2023.webp",
        name: "Худи Mercedes 2023",
        description: "",
    },
    {
        id: 29,
        category: "Худи",
        price: 14990,
        image: "../images/худи сайнс вегас.webp",
        name: "Худи Ferrari Sainz Vegas GP",
        description: "",
    },
    {
        id: 30,
        category: "Брелоки",
        price: 999,
        image: "../images/брелок ред булл.webp",
        name: "Брелок Red Bull Racing 2023",
        description: "",
    },
    {
        id: 31,
        category: "Футболки",
        price: 1999,
        image: "../images/Футболка Red Bull Constructors Cup 2023.png",
        name: "Футболка Red Bull Constructors Champions 2023",
        description: "",
    },
    {
        id: 32,
        category: "Брелоки",
        price: 999,
        image: "../images/брелок астон.webp",
        name: "Брелок Aston Martin 2023",
        description: "",
    },
    {
        id: 33,
        category: "Постеры",
        price: 899,
        image: "../images/Постер Sainz 21.jpg",
        name: "Постер Ferrari Sainz 2021",
        description: "",
    },
    {
        id: 34,
        category: "Брелоки",
        price: 999,
        image: "../images/брелок сенна.webp",
        name: "Брелок шлем Senna",
        description: "",
    },
    {
        id: 35,
        category: "Брелоки",
        price: 999,
        image: "../images/брелок макларен.webp",
        name: "Брелок McLaren 2023",
        description: "",
    },
    {
        id: 36,
        category: "Футболки",
        price: 2499,
        image: "../images/футболка VER_33.png",
        name: "Футболка Max Verstappen Logo",
        description: "",
    },
    {
        id: 37,
        category: "Худи",
        price: 3499,
        image: "../images/Худи Aston Martin 2023.jpg",
        name: "Худи Aston Martin 2023",
        description: "",
    },
    {
        id: 38,
        category: "Футболки",
        price: 1999,
        image: "../images/футболка хас.jpg",
        name: "Футболка Haas 2023",
        description: "",
    },
    {
        id: 39,
        category: "Футболки",
        price: 1999,
        image: "../images/Футболка Aston Martin Racing.png",
        name: "Футболка Aston Martin",
        description: "",
    },
    {
        id: 40,
        category: "Кепки",
        price: 2499,
        image: "../images/кепка формула 1 голубая.webp",
        name: "Кепка Formula 1 Pastel",
        description: "",
    },
    {
        id: 41,
        category: "Футболки",
        price: 2499,
        image: "../images/футболка формула 1 бежевый.webp",
        name: "Футболка Formula 1 Pastel",
        description: "",
    },
    {
        id: 42,
        category: "Футболки",
        price: 3499,
        image: "../images/футболка месесдес стэлс.webp",
        name: "Футболка Mercedes Stealth",
        description: "",
    },
    {
        id: 43,
        category: "Футболки",
        price: 3499,
        image: "../images/Verstappen 2023 Fanwear T-Shirt.webp",
        name: "Футболка Verstappen 2023 Fanwear",
        description: "",
    },
    {
        id: 44,
        category: "Модели",
        price: 14990,
        image: "../images/модель макларен сенна.jpg",
        name: "Модель McLaren Ford MP4/1C Senna 1:43",
        description: "",
    },
    {
        id: 45,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка мерседес черный.webp",
        name: "Кепка Mercedes 2023",
        description: "",
    },
    {
        id: 46,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка альфа таури.webp",
        name: "Кепка Alpha Tauri 2023",
        description: "",
    },
    {
        id: 47,
        category: "Кепки",
        price: 1999,
        image: "../images/кепка 9fforty макларен.webp",
        name: "Кепка 9FORTY McLaren 2023",
        description: "",
    },
    {
        id: 48,
        category: "Кепки",
        price: 2499,
        image: "../images/Norris 2023 Silverstone Cap.webp",
        name: "Кепка McLaren Norris 2023 Silverstone GP",
        description: "",
    },
    {
        id: 49,
        category: "Кепки",
        price: 2499,
        image: "../images/Alonso 2023 Spanish GP Cap SE.webp",
        name: "Кепка Aston Martin Alonso 2023 Spanish GP",
        description: "",
    },
    {
        id: 50,
        category: "Кепки",
        price: 1999,
        image: "../images/McLaren 2023 Team Cap.webp",
        name: "Кепка McLaren 2023",
        description: "",
    },
    {
        id: 51,
        category: "Кепки",
        price: 1999,
        image: "../images/Formula 1Large Logo Cap.webp",
        name: "Кепка Formula 1",
        description: "",
    },
    {
        id: 52,
        category: "Кепки",
        price: 2499,
        image: "../images/кепка мерседес белый.webp",
        name: "Кепка Mercedes 2023",
        description: "",
    },
    {
        id: 53,
        category: "Шлемы",
        price: 24990,
        image: "../images/George Russell 63 Official 2023 Helmet.webp",
        name: "Шлем Russell 63 Mercedes 2023 1:2",
        description: "",
    },
    {
        id: 54,
        category: "Шлемы",
        price: 29990,
        image: "../images/Ayrton Senna 1994 Mini Helmet.webp",
        name: "Шлем Senna 1994 1:2",
        description: "",
    },
    {
        id: 55,
        category: "Модели",
        price: 34990,
        image: "../images/MCL36 4 Norris Signature Car Model.webp",
        name: "Модель McLaren MCL36 Ricciardo 1:23",
        description: "",
    },
    {
        id: 56,
        category: "Модели",
        price: 29990,
        image: "../images/C42 Alfa Romeo 2022 Bottas Car Model.webp",
        name: "Модель Alfa Romeo C42 Bottas 1:23",
        description: "",
    },
    {
        id: 57,
        category: "Худи",
        price: 5999,
        image: "../images/2023 Alonso Hoody.webp",
        name: "Худи Alonso 2023",
        description: "",
    },
    {
        id: 58,
        category: "Постеры",
        price: 899,
        image: "../images/Постер Alonso 2005.jpg",
        name: "Постер Renault Alonso 2005",
        description: "",
    },
    {
        id: 59,
        category: "Постеры",
        price: 899,
        image: "../images/Постер Ayrton Senna.jpg",
        name: "Постер McLaren Senna",
        description: "",
    },
    {
        id: 60,
        category: "Постеры",
        price: 899,
        image: "../images/Постер Lando Norris Monaco 21.jpg",
        name: "Постер McLaren Norris Monaco 21",
        description: "",
    },
]